# Generated by Django 6.0.4 on 2026-04-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceuser',
            name='is_admin',
        ),
    ]
