# Generated by Django 6.0.4 on 2026-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_balanceuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceuser',
            name='currency_type',
            field=models.CharField(choices=[('GDP', 'GDP'), ('USD', 'USD'), ('EUR', 'EUR')], default='GDP', max_length=3),
        ),
    ]
