# Generated by Django 6.0.4 on 2026-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_balanceuser_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceuser',
            name='currency_type',
            field=models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('EUR', 'EUR')], default='GBP', max_length=3),
        ),
    ]
