# Generated by Django 6.0.3 on 2026-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancetransactions',
            old_name='from_username',
            new_name='payee_username',
        ),
        migrations.RenameField(
            model_name='balancetransactions',
            old_name='to_username',
            new_name='recipient_username',
        ),
    ]
