# Generated by Django 6.0.3 on 2026-04-03 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_rename_from_username_balancetransactions_payee_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransactions',
            name='transacted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
