# Generated by Django 6.0.3 on 2026-04-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_balancetransactions_transacted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancetransactions',
            old_name='transacted',
            new_name='created_at',
        ),
    ]
