# Generated by Django 6.0.3 on 2026-04-03 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_balancetransactions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2026, 4, 3, 12, 25, 32, 922812, tzinfo=datetime.timezone.utc)),
        ),
    ]
