# Generated by Django 6.0.3 on 2026-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0008_alter_balancetransactions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
