# Generated by Django 6.0.3 on 2026-04-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0010_balancetransactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransactionrequest',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
