# Generated by Django 6.0.3 on 2026-04-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0011_balancetransactionrequest_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransactionrequest',
            name='state',
            field=models.CharField(default='Open/No response', max_length=150),
        ),
    ]
