# Generated by Django 6.0.3 on 2026-04-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0012_balancetransactionrequest_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetransactionrequest',
            name='state',
        ),
    ]
