# Generated by Django 6.0.3 on 2026-04-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0013_remove_balancetransactionrequest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransactions',
            name='transaction_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payapp.balancetransactionrequest'),
        ),
    ]
