# Generated by Django 6.0.3 on 2026-04-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0014_balancetransactions_transaction_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceTransactions',
            new_name='BalanceTransaction',
        ),
    ]
