# Generated by Django 6.0.4 on 2026-04-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0015_rename_balancetransactions_balancetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetransaction',
            name='transaction_request',
        ),
    ]
