# Generated by Django 6.0.4 on 2026-04-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0016_remove_balancetransaction_transaction_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
