# Generated by Django 6.0.4 on 2026-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0017_delete_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='currency_type',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='balancetransactionrequest',
            name='currency_type',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
